#+ endpoint: http://52.19.213.234:7200/repositories/TBFY

prefix ocds:<http://www.sintef.no/ontology/ocds/>

select distinct ?s ?n where {
    ?s a ocds:Organisation .
    ?s ocds:hasName ?n
} LIMIT 100
